// This file is auto-generated by your-router-gen. Do not modify.

/**
 * Type-safe route helpers generated from your file-based routing.
 * Use these functions for safe navigation and link creation.
 */
export const Routes = {
  about: () => "/about",
  contact: () => "/contact",
  home: () => "/",
  products: () => "/products",
  

   blog: (params: { slug: string }) => `/blog/${params.slug}`,

   
};

/**
 * Union type of all generated route names.
 */
export type RouteNames = keyof typeof Routes;

/**
 * Union type of all generated route paths (the actual URL strings).
 */
export type RoutePaths = ReturnType<typeof Routes[RouteNames]>;
