// This file is auto-generated by your-router-gen. Do not modify.

/**
 * Type-safe route helpers generated from your file-based routing.
 * Use these functions for safe navigation and link creation.
 */
export const Routes = {
  about: () => "/about",
  blogs.slug: (params: { slug: string }) => `/blogs/${params.slug}`,
  contact: () => "/contact",
  docs.slug: (params?: { slug?: string[] }) => `/docs/${params.slug?.join('/') || ''}`,
  home: () => "/",
  products: () => "/products",
};

/**
 * Union type of all generated route names.
 */
export type RouteNames = keyof typeof Routes;

/**
 * Union type of all generated route paths (the actual URL strings).
 */
export type RoutePaths = ReturnType<typeof Routes[RouteNames]>;
